# Generated by Django 3.2 on 2021-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlindSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'db_secret',
            },
        ),
        migrations.CreateModel(
            name='ClothingStore',
            fields=[
                ('barcode', models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.TextField(max_length=200, null=True)),
                ('manufacturer', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'db_clothing_shop',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'db_employees',
            },
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_pass', models.CharField(max_length=200, null=True)),
                ('prize', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'secret_safe',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'db_users',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('car_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_of_accidents', models.IntegerField(null=True)),
                ('manufacturer', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('total_km', models.FloatField(null=True)),
                ('is_automatic', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'db_vehicles',
            },
        ),
    ]
