# Generated by Django 3.0.11 on 2021-02-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("problems", "0002_init_problems_data_tables")
                    ]

    operations = [
        migrations.RunSQL([
            "CREATE USER user_problems  WITH PASSWORD '123456';",
            "GRANT CONNECT ON DATABASE postgres TO user_problems;",
            "GRANT SELECT ON ALL TABLES IN SCHEMA public TO user_problems;"
        ])
    ]
