# Generated by Django 3.0.4 on 2021-01-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyUser',
            fields=[
                ('username', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'db_dummy_users',
            },
        ),
    ]
