# Generated by Django 3.0.4 on 2021-02-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsContentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=200, null=True)),
                ('hreference', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'db_problems_content_table',
            },
        ),
    ]
