version: '3.9'

services:
  db:
    container_name: postgres_database
    image: postgres:12.0-alpine
    expose: 
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql3/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"

  sql_training:
    container_name: web
    build: 
      context: .
    expose: 
      - "8000"
    ports: 
      - "8000:8000"
    volumes: 
      - ./sql_training:/sql_training
    environment: 
      - DEBUG=1
    env_file:
      - ./.env.dev
    links: 
      - db
    depends_on:
      - db
#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - sql_training
#  certbot:
#    image: certbot/certbot

volumes:
  postgres_data: